# This is an example mods.toml file. It contains the data relating to the loading mods.
# There are several mandatory fields (#mandatory), and many more that are optional (#optional).
# The overall format is standard TOML format, v0.5.0.
# Note that there are a couple of TOML lists in this file.
# Find more information on toml format here:  https://github.com/toml-lang/toml
# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
#modLoader="javafml" #mandatory#
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
#loaderVersion="[44,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
modLoader = "kotlinforforge"
# Change this if you require a certain version of KotlinForForge
loaderVersion = "[4,)"

license = "All rights reserved"
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
# The modid of the mod
modId = "smm" #mandatory
version = "${file.jarVersion}" #mandatory
displayName = "smm mod" #mandatory
logoFile = "smm.png" #optional
credits = "Klosw,AmarokIce" #optional
authors = "Klosw" #optional

description = '''
 A simple mod that offers [tpa, tphere, tpaccept, tpadeny ,back,trp,home] by AmarokIce.OMO
 '''
[[dependencies.smm]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[44,)" #mandatory
ordering = "NONE"
side = "BOTH"
[[dependencies.smm]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.3,1.20)"
ordering = "NONE"
side = "BOTH"
